### ISSUE TITLE
teleprompter: The right margin covers the text

### ISSUE THREAD

**Issue by michelemendel** [jonegil/gui-with-gio#30] opened 2023-03-10 14:13 UTC
<img width="654" alt="Screenshot 2023-03-10 at 15 03 48" src="https://user-images.githubusercontent.com/14011/224338032-81f0853e-92ce-4c91-9a47-7194d835ee62.png">

Changing 
`marginWidth = (unit.Dp(gtx.Constraints.Max.X) - textWidth) / 2`
to
`marginWidth = (unit.Dp(gtx.Constraints.Max.X) - textWidth) / 4`
fixed the problem, but I don't see why.

**Comment by jonegil** [comment] 2023-03-17 23:00
Thank you for the comment. 
How big of a screen are you running this on?

**Comment by jonegil** [comment] 2023-05-01 20:53
I know the root cause, and it's by design to have borders left and right that squeezes the text into the middle. 

However, depending on screen resolution, the squeeze is  potentially too large which is why your adjustment makes it visible again. 

Closing this for now.

**Closed** 2023-05-01 20:53 UTC
